export interface Quote {
  text: string
  author: string
}

export const QUOTES: Quote[] = [
  { text: 'Doing good is more important than doing well.', author: 'Unknown' },
  { text: 'This above all: to thine own self be true.', author: 'Shakespeare' },
  { text: 'No side goes into battle and comes out with more people.', author: 'Heraclitus' },
  { text: 'If every problem had an easy solution, would they really be problems.', author: 'Unknown' },
  { text: "My greatest fear is that the day I stand before god, he shows me a man much greater than I and says 'this is who you could've been.'", author: 'Unknown' },
  { text: 'Train till failure or stay a failure.', author: 'Unknown' },
  { text: 'With great power comes great responsibility.', author: 'Spider-Man' },
  { text: 'A winner is a loser who tries one more time.', author: 'George M. Moore Jr.' },
  { text: "What you're not changing, you're choosing.", author: 'Unknown' },
  { text: "You waste your precious time dreaming of the future instead of engaging in the present. Since nothing seems urgent to you, you're only half involved in what you do.", author: 'Unknown' },
  { text: "We don't build trust by offering help. We build trust by asking for it.", author: 'Simon Sinek' },
  { text: "You can have a 100 problems in life until you face a health problem, then it becomes the only problem.", author: 'Unknown' },
  { text: "Communication is a form of respect, and if you respect the person, you'll get back to them as soon as you possibly can.", author: 'Unknown' },
  { text: 'The day the blind man sees, the first thing he throws away is the stick that helped him all his life.', author: 'Unknown' },
  { text: 'Search for everything except love and death. They will find you when the time comes.', author: 'Unknown' },
  { text: "Your time is limited, so don't waste it living someone else's life.", author: 'Steve Jobs' },
  { text: 'Every action you take is a vote for the type of person you wish to become.', author: 'James Clear' },
  { text: 'Some people talk to you in their free time. Some people free their time to talk to you. Know the difference.', author: 'Unknown' },
  { text: "Don't call me lucky. I've failed more than you've ever tried.", author: 'Unknown' },
  { text: "If it doesn't bring peace, profits, or purpose, then don't give it your time, energy, or attention.", author: 'Unknown' },
  { text: 'No results? Keep working. Bad results? Keep working. Good results? Keep working.', author: 'Unknown' },
  { text: "You're never ready for what you have to do. You just do it. That makes you ready.", author: 'Unknown' },
  { text: 'Start where you are. Use what you have. Do what you can.', author: 'Arthur Ashe' },
  { text: "Everybody is a genius. But if you judge a fish by its ability to climb a tree, it will live its whole life believing that it is stupid.", author: 'Albert Einstein' },
  { text: 'This too shall pass.', author: 'Persian proverb' },
  { text: "Everything's impossible until somebody does it.", author: 'Batman' },
  { text: 'My unmatched perspicacity coupled with my sheer indefatigability makes me a feared opponent in any realms of human endeavor.', author: 'Andrew Tate' },
  { text: "It's an imperfect world, but it's the only one we've got.", author: 'Iron Man' },
  { text: "A hero can be anyone. Even a man doing something as simple and reassuring as putting a coat around a young boy's shoulders to let him know the world hadn't ended.", author: 'Batman' },
  { text: "If you make yourself more than just a man, if you devote yourself to an ideal, and if they can't stop you, then you become something else entirely. A legend.", author: 'Batman' },
  { text: "I don't get lucky. I make my own luck.", author: 'Harvey Specter' },
  { text: 'Wake up determined. Go to bed satisfied.', author: 'Dwayne Johnson' },
  { text: 'Your mind must be stronger than your feelings.', author: 'Unknown' },
  { text: 'You are the only person who can make this work, and you are the only person who can mess this up.', author: 'Unknown' },
  { text: "Action is the only way you'll progress. Not talking. Not planning. And not reading books.", author: 'Unknown' },
  { text: 'Knowing is not enough; we must apply. Willing is not enough; we must do.', author: 'Bruce Lee' },
  { text: 'Do not fear.', author: 'Bible' },
  { text: 'First part of your life you learn. Second part of your life you earn. Third part of your life you return.', author: 'Unknown' },
  { text: 'No man has the right to be an amateur in the matter of physical training. It is a shame for a man to grow old without seeing the beauty and strength of which his body is capable.', author: 'Socrates' },
  { text: 'Life consists of what a man is thinking about all day.', author: 'Ralph Waldo Emerson' },
  { text: "You can't blend in when you were born to stand out.", author: 'Unknown' },
  { text: 'Love is not a feeling. It\'s a choice. Same goes with hate.', author: 'Unknown' },
  { text: "Life isn't happening to you; life is happening from you.", author: 'Tony Robbins' },
  { text: "Take the risk. If you win, you'll be happy. If you lose, you'll be wiser.", author: 'Unknown' },
  { text: 'Before you give up, remember why you started.', author: 'Unknown' },
  { text: "Don't stop when you're tired. Stop when you're done.", author: 'David Goggins' },
  { text: "I don't have dreams, I have goals, and now I'm onto my next one.", author: 'Harvey Specter' },
  { text: "I refuse to answer that on the grounds that I don't want to.", author: 'Harvey Specter' },
  { text: "I'm against having emotions, not using them.", author: 'Harvey Specter' },
  { text: "Win a no-win situation by rewriting the rules.", author: 'Harvey Specter' },
  { text: "That's the difference between you and me. You want to lose small, I want to win big.", author: 'Harvey Specter' },
  { text: 'Loyalty is a two-way street. If I am asking it from you, then you are getting it from me.', author: 'Harvey Specter' },
  { text: 'Ever loved someone so much you would do anything for them? Yeah, well, make that someone yourself, and do whatever the hell you want.', author: 'Harvey Specter' },
  { text: "Create a situation where failure isn't even a possibility.", author: 'Unknown' },
  { text: 'Everything around you was made by people no smarter than you, and you can change it.', author: 'Steve Jobs' },
  { text: "We don't fall in love with the other person. We fall in love with the version of us that we get to be through and with the other person.", author: 'Unknown' },
  { text: "It's nice to be important, but it's more important to be nice.", author: 'Unknown' },
  { text: 'A mistake that made you humble is better than an achievement that made you arrogant.', author: 'Unknown' },
  { text: "Tired is only in the mind. If you tell yourself you're tired, then you're going to be tired. I don't get tired.", author: 'LeBron James' },
  { text: 'Life is a tragedy when seen in close up and a comedy in long shot.', author: 'Charlie Chaplin' },
  { text: '꿈의 크기가 그 사람의 그릇을 정한다.', author: 'Unknown' },
  { text: "There's still a best move on the board regardless of how fucked up your position is.", author: 'Andrew Tate' },
  { text: 'Learn to select your thoughts the same way you select your clothes every day.', author: 'Unknown' },
  { text: 'That which does not kill us makes us stronger.', author: 'Friedrich Nietzsche' },
  { text: 'Be the change that you wish to see in the world.', author: 'Unknown' },
  { text: '인생은 성공과 과정만 있다. 실패는 존재하지 않는다.', author: 'Unknown' },
  { text: 'Yesterday, I was clever, so I wanted to change the world. Today, I\'m wise, so I\'m changing myself.', author: 'Rumi' },
  { text: "The definition of anger is an emotional punishment you give yourself for somebody else's behavior.", author: 'Unknown' },
  { text: "Consider how hard it is to change yourself. Then you'll understand how foolish it is to think you can change someone else.", author: 'Unknown' },
  { text: "Your day doesn't start when you wake up. It starts before you go to bed.", author: 'Unknown' },
  { text: "What are you so afraid of losing when nothing in this world belongs to you in the first place?", author: 'Unknown' },
  { text: "The greatest pleasure I've had is trying to do something that everybody said could not be done.", author: 'Walt Disney' },
  { text: "You're never wrong to do the right thing.", author: 'Mark Twain' },
  { text: "You can lose a lot of money chasing bitches, but you'll never lose bitches chasing money.", author: 'Unknown' },
  { text: "Humble enough to know that you can be replaced. Wise enough to know that there's nobody else like you.", author: 'Unknown' },
  { text: "You have enemies? Good. That means you've stood up for something, sometime in your life.", author: 'Winston Churchill' },
  { text: 'Only a human mind could invent something as insipid as love.', author: 'The Matrix' },
  { text: 'The first step is to establish that something is possible; then probability will occur.', author: 'Elon Musk' },
  { text: 'Study hard what interests you the most in the most undisciplined, irreverent, and original manner possible.', author: 'Richard Feynman' },
  { text: 'He who has a why to live can bear almost any how.', author: 'Friedrich Nietzsche' },
  { text: 'As long as I am alive, I have infinite chances.', author: 'Luffy' },
  { text: "I don't remember the name of every weakling I crush.", author: 'Mihawk' },
  { text: 'Genius is eternal patience.', author: 'Michelangelo' },
  { text: 'If you cannot do great things, do small things in a great way.', author: 'Napoleon Hill' },
]

export function getDailyQuote(): Quote {
  const start = new Date(new Date().getFullYear(), 0, 0)
  const diff = Date.now() - start.getTime()
  const dayOfYear = Math.floor(diff / 86_400_000)
  return QUOTES[dayOfYear % QUOTES.length]
}
